# Generated by Django 4.1.7 on 2023-04-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADDITIONAL_INFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_type', models.CharField(choices=[('Non-Semestered', 'Non-Semestered'), ('Semestered', 'Semestered')], default='Semestered', max_length=14)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school_board', models.CharField(choices=[('OCDSB', 'OCDSB'), ('OCSB', 'OCSB'), ('N/A', 'N/A')], default='OCDSB', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CSV_FILE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField()),
                ('prep_times', models.TextField()),
                ('locations', models.TextField()),
            ],
        ),
    ]
