# Generated by Django 4.1.7 on 2023-04-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ADDITIONAL_INFO',
            new_name='additional_info_models',
        ),
    ]
